development:
  adapter: postgresql
  encoding: unicode
  database: featyre_development
  pool: 5
  username: ctres
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: featyre_test
  pool: 5
  username: myapp
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: featyre_production
  pool: 5
  username: featyre
  password: